Moving IO docs from gf180mcu-pdk
google/globalfoundries-pdk-libs-gf180mcu_fd_io pull request #2
Opened 2022-07-25 13:13 UTC by mohanad0mohamed

Fixes #https://github.com/google/gf180mcu-pdk/issues/12

- Moved all documentations in docs directory.
- Made symbolic link for it in [gf180mcu-pdk](https://github.com/google/gf180mcu-pdk)

- [x] Built locally with no errors

2022-07-28 00:29 UTC, mithro commented
This pull request should include a link to the pull request at https://github.com/google/gf180mcu-pdk/pull/34 in the description.

2022-07-28 01:10 UTC, mithro requested changes
Fixes are needs;
 * There are a couple of accidental file removals.
 * Fix the names of the rst files.

2022-07-28 01:10 UTC, mithro commented on docs/code-of-conduct.rst
> -Google Open Source Community Guidelines
Why are you deleting this file?

2022-07-28 01:10 UTC, mithro commented on docs/contributing.rst
> -How to Contribute
Why are you deleting this file?

2022-07-28 01:10 UTC, mithro commented on docs/gf180mcu_fd_io__2.rst
> +2.0 Library Features
This file should be called `features.rst`

2022-07-28 01:10 UTC, mithro commented on docs/gf180mcu_fd_io__3.rst
> +3.0 Naming Convention
This file should be called something like `naming.rst`

2022-07-28 01:10 UTC, mithro commented on docs/gf180mcu_fd_io__4_1.rst
> +4.1 Digital I/O Cell Control Pins
This file should be called something like `functional/digital.rst`

2022-07-28 01:10 UTC, mithro commented on docs/gf180mcu_fd_io__4_2.rst
> +4.2 Tri-state Programmable Digital I/O Cell
This file should be called something like `functional/trisate.rst`

2022-07-28 01:10 UTC, mithro commented on docs/gf180mcu_fd_io__4_4.rst
> +4.4 Input Only I/O Cell
This file should be called something like `functional/input_only.rst`

2022-07-28 01:10 UTC, mithro commented on docs/gf180mcu_fd_io__4_5.rst
> +4.5 Analogue Signal Cells
This file should be called something like `analog.rst`

2022-07-28 01:10 UTC, mithro commented on docs/gf180mcu_fd_io__4_6.rst
> +4.6 Power supply pads and Corner pad
This file should be called something like `power.rst`

2022-07-28 01:10 UTC, mithro commented on docs/gf180mcu_fd_io__5.rst
> +5.0 Specifications
This file should be called something like `specs.rst`

2022-07-28 01:10 UTC, mithro commented on docs/gf180mcu_fd_io__5_1.rst
> +Operating Conditions
This file should be called something like `specs/conditions.rst`

2022-07-28 01:10 UTC, mithro commented on docs/gf180mcu_fd_io__5_2.rst
> +==============
This file should be called something like `spec/esd.rst`

2022-07-28 01:10 UTC, mithro commented on docs/gf180mcu_fd_io__5_3.rst
> +Latchup Immunity
This file should be called something like `spec/latchup.rst`

2022-07-28 01:10 UTC, mithro commented on docs/gf180mcu_fd_io__5_4.rst
> +Electrical Characteristics (DVDD = 4.50V to 5.50V, Temp = -40 degC to 125 degC)
This file should be called something like `specs/electrical.rst`

2022-07-28 01:10 UTC, mithro commented on docs/gf180mcu_fd_io__5_5.rst
> +Input Propagation Delay (DVDD = 4.50V to 5.50V, Temp = -40 degC to 125 degC)
This file should be called something like `specs/delay_input.rst`

2022-07-28 01:10 UTC, mithro commented on docs/gf180mcu_fd_io__5_6.rst
> +Output Propagation Delay (DVDD = 4.50V to 5.50V, Temp = -40 degC to 125 degC)
This file should be called something like `specs/delay_output.rst`

2022-07-28 01:10 UTC, mithro commented on docs/gf180mcu_fd_io__5_7.rst
> +Characterization Corners
This file should be called something like `specs/corners.rst`

2022-07-28 08:36 UTC, mohanad0mohamed commented on docs/code-of-conduct.rst
> -Google Open Source Community Guidelines
Already available in the commit that made a symbolic link to [open-source-pdks](https://github.com/google/open-source-pdks) so I had removed it.

2022-07-28 08:36 UTC, mohanad0mohamed commented on docs/contributing.rst
> -How to Contribute
Already available in the commit that made a symbolic link to [open-source-pdks](https://github.com/google/open-source-pdks) so I had removed it.

2022-07-28 09:59 UTC, mohanad0mohamed commented on docs/code-of-conduct.rst
> -Google Open Source Community Guidelines
Also, it gives warning because it's not referenced in any other `.rst` file.

2022-07-28 09:59 UTC, mohanad0mohamed commented on docs/contributing.rst
> -How to Contribute
Also, it gives warning because it's not referenced in any other `.rst` file.

2022-07-28 10:18 UTC, mohanad0mohamed commented on docs/gf180mcu_fd_io__2.rst
> +2.0 Library Features
Done

2022-07-28 10:18 UTC, mohanad0mohamed commented on docs/gf180mcu_fd_io__4_1.rst
> +4.1 Digital I/O Cell Control Pins
Done

2022-07-28 10:18 UTC, mohanad0mohamed commented on docs/gf180mcu_fd_io__4_2.rst
> +4.2 Tri-state Programmable Digital I/O Cell
Done

2022-07-28 10:19 UTC, mohanad0mohamed commented on docs/gf180mcu_fd_io__4_5.rst
> +4.5 Analogue Signal Cells
Done

2022-07-28 10:19 UTC, mohanad0mohamed commented on docs/gf180mcu_fd_io__5.rst
> +5.0 Specifications
Done

2022-07-28 10:19 UTC, mohanad0mohamed commented on docs/gf180mcu_fd_io__5_2.rst
> +==============
Done

2022-07-28 10:19 UTC, mohanad0mohamed commented on docs/gf180mcu_fd_io__5_4.rst
> +Electrical Characteristics (DVDD = 4.50V to 5.50V, Temp = -40 degC to 125 degC)
Done

2022-07-28 10:19 UTC, mohanad0mohamed commented on docs/gf180mcu_fd_io__5_6.rst
> +Output Propagation Delay (DVDD = 4.50V to 5.50V, Temp = -40 degC to 125 degC)
Done

2022-07-28 10:19 UTC, mohanad0mohamed commented on docs/gf180mcu_fd_io__3.rst
> +3.0 Naming Convention
Done

2022-07-28 10:19 UTC, mohanad0mohamed commented on docs/gf180mcu_fd_io__4_4.rst
> +4.4 Input Only I/O Cell
Done

2022-07-28 10:19 UTC, mohanad0mohamed commented on docs/gf180mcu_fd_io__4_6.rst
> +4.6 Power supply pads and Corner pad
Done

2022-07-28 10:20 UTC, mohanad0mohamed commented on docs/gf180mcu_fd_io__5_1.rst
> +Operating Conditions
Done

2022-07-28 10:20 UTC, mohanad0mohamed commented on docs/gf180mcu_fd_io__5_3.rst
> +Latchup Immunity
Done

2022-07-28 10:20 UTC, mohanad0mohamed commented on docs/gf180mcu_fd_io__5_5.rst
> +Input Propagation Delay (DVDD = 4.50V to 5.50V, Temp = -40 degC to 125 degC)
Done

2022-07-28 10:20 UTC, mohanad0mohamed commented on docs/gf180mcu_fd_io__5_7.rst
> +Characterization Corners
Done

2022-07-28 10:21 UTC, mohanad0mohamed commented
Made the requested changes

2022-07-28 11:09 UTC, mohanad0mohamed commented on docs/code-of-conduct.rst
> -Google Open Source Community Guidelines
I have retrieved them but not inside `docs`, instead I put them outside not to produce warnings.

2022-07-28 11:09 UTC, mohanad0mohamed commented on docs/contributing.rst
> -How to Contribute
I have retrieved them but not inside `docs`, instead I put them outside not to produce warnings.

2022-07-28 11:42 UTC, mohanad0mohamed commented
I have retrieved `contributing.rst` and `code_of_conduct.rst` but not inside docs, instead I put them outside not to produce warnings.

2022-08-02 21:33 UTC, mithro approved these changes
I have removed the unrelated changes around `contributing` / `code-of-conduct` and the `README.rst` name fix from this pull request.

2022-08-02 23:24 UTC, merged